# Generated by Django 5.1.3 on 2024-12-28 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aadhar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('mobile', models.BigIntegerField(unique=True)),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('img', models.ImageField(upload_to='Images')),
                ('gender', models.CharField(max_length=32)),
                ('address', models.TextField()),
                ('fathers_name', models.CharField(max_length=100)),
                ('mothers_name', models.CharField(max_length=100)),
                ('aadhar', models.BigIntegerField(unique=True)),
                ('otp', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
